const now = Date.now();

export const services = [
  {
    id: 'checkout-api',
    name: 'checkout-api',
    namespace: 'commerce',
    protocol: 'HTTP',
    port: 8000,
    targetGroup: 'tg-commerce-checkout-api-8000',
    targetHealth: 'healthy',
    endpoint: 'http://checkout-api.commerce.svc.cluster.local:8000',
    methods: ['GET', 'POST'],
    source: 'ALB target group + Kubernetes service fallback',
  },
  {
    id: 'payment-api',
    name: 'payment-api',
    namespace: 'commerce',
    protocol: 'HTTP',
    port: 8001,
    targetGroup: 'tg-commerce-payment-api-8001',
    targetHealth: 'unhealthy',
    endpoint: 'http://payment-api.commerce.svc.cluster.local:8001',
    methods: ['POST'],
    source: 'ALB target group metadata',
  },
  {
    id: 'inventory-api',
    name: 'inventory-api',
    namespace: 'supply',
    protocol: 'HTTP',
    port: 8000,
    targetGroup: 'tg-supply-inventory-api-8000',
    targetHealth: 'healthy',
    endpoint: 'http://inventory-api.supply.svc.cluster.local:8000',
    methods: ['GET'],
    source: 'Kubernetes service annotation api-method=GET',
  },
  {
    id: 'customer-api',
    name: 'customer-api',
    namespace: 'identity',
    protocol: 'HTTP',
    port: 8000,
    targetGroup: 'tg-identity-customer-api-8000',
    targetHealth: 'healthy',
    endpoint: 'http://customer-api.identity.svc.cluster.local:8000',
    methods: ['GET', 'POST'],
    source: '/openapi.json discovery',
  },
];

export const spans = [
  {
    traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
    spanId: 'root001a92f3577b',
    parentSpanId: null,
    serviceName: 'checkout-api',
    name: 'POST /checkout',
    kind: 'SERVER',
    startMs: now - 180000,
    durationMs: 812,
    statusCode: 'ERROR',
    httpStatusCode: 502,
    route: '/checkout',
    metadata: { 'http.method': 'POST', 'k8s.namespace.name': 'commerce', 'service.version': '1.8.3' },
  },
  {
    traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
    spanId: 'clientpay92f3577',
    parentSpanId: 'root001a92f3577b',
    serviceName: 'checkout-api',
    name: 'POST payment-api /authorize',
    kind: 'CLIENT',
    startMs: now - 179710,
    durationMs: 458,
    statusCode: 'ERROR',
    httpStatusCode: 500,
    route: '/authorize',
    metadata: { 'peer.service': 'payment-api', 'net.peer.port': 8001 },
  },
  {
    traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
    spanId: 'serverpay2f3577',
    parentSpanId: 'clientpay92f3577',
    serviceName: 'payment-api',
    name: 'POST /authorize',
    kind: 'SERVER',
    startMs: now - 179690,
    durationMs: 414,
    statusCode: 'ERROR',
    httpStatusCode: 500,
    route: '/authorize',
    metadata: { 'exception.type': 'PaymentGatewayTimeout', 'exception.message': 'gateway timeout after 400ms' },
  },
  {
    traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
    spanId: 'inventory2f3577',
    parentSpanId: 'root001a92f3577b',
    serviceName: 'inventory-api',
    name: 'GET /reserve-status',
    kind: 'CLIENT',
    startMs: now - 179540,
    durationMs: 123,
    statusCode: 'OK',
    httpStatusCode: 200,
    route: '/reserve-status',
    metadata: { 'peer.service': 'inventory-api' },
  },
  {
    traceId: 'ab12cd3477b34da6a3ce929d0e0e7788',
    spanId: 'roothealthy0001',
    parentSpanId: null,
    serviceName: 'customer-api',
    name: 'GET /customers/42',
    kind: 'SERVER',
    startMs: now - 420000,
    durationMs: 146,
    statusCode: 'OK',
    httpStatusCode: 200,
    route: '/customers/:id',
    metadata: { 'http.method': 'GET', 'cache.hit': true },
  },
];

export const logs = [
  { traceId: spans[0].traceId, spanId: spans[0].spanId, timestamp: now - 179980, serviceName: 'checkout-api', severity: 'INFO', message: 'accepted checkout request cart_id=cart-8842' },
  { traceId: spans[0].traceId, spanId: spans[1].spanId, timestamp: now - 179700, serviceName: 'checkout-api', severity: 'INFO', message: 'calling payment-api authorize with propagated traceparent header' },
  { traceId: spans[0].traceId, spanId: spans[2].spanId, timestamp: now - 179450, serviceName: 'payment-api', severity: 'ERROR', message: 'PaymentGatewayTimeout: upstream gateway timeout after 400ms' },
  { traceId: spans[0].traceId, spanId: spans[0].spanId, timestamp: now - 179210, serviceName: 'checkout-api', severity: 'ERROR', message: 'downstream payment-api failed; returning 502 to caller' },
  { traceId: spans[4].traceId, spanId: spans[4].spanId, timestamp: now - 419900, serviceName: 'customer-api', severity: 'INFO', message: 'customer profile served from cache' },
];
